server:
  port: 8080

spring:
  profiles:
    active: local

sprin.batch.job.names: ${job.name:NONE}



#local 환경
---
spring:
  profiles: local
  datasource:
    data: classpath:data-h2.sql #시작할때 실행시킬 script
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  redis:
    host: localhost
    port: 6379

#mysql
---
spring:
  profiles: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/test?useUnicode=true&charaterEncoding=utf-8
      username: root
      password: root1234
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379